version: "3.7"

services:

  database:
    image: postgres:9.4
    restart: unless-stopped
    ports: 
      - "5432:5432"
    expose: 
      - "5432"
    volumes:
      - dbData:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: marble

  marble-app:
    image: node:12.3.1-alpine
    volumes: 
      - ./:/home/node/app
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on: 
      - database
    working_dir: /home/node/app
    environment:
      - AUTH_SECRET=asdf;lkj
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=admin
      - DATABASE_USER=admin
      - DATABASE_DB=marble
      - PORT=3001
      - REACT_APP_API=localhost
    command: "npm start"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes: 
  dbData: